Traceback (most recent call last):
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from hydrodataset.camels import Camels

camels_us_path = os.path.join("camels", "camels_us")
us_region = "US"
camels_us = Camels(camels_us_path, region=us_region)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mPermissionError[0m                           Traceback (most recent call last)
File [0;32m/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/hydrodataset/__init__.py:36[0m
[1;32m     35[0m [38;5;28;01mtry[39;00m:
[0;32m---> 36[0m     [43mhydrodataset_root_dir[49m[38;5;241;43m.[39;49m[43mmkdir[49m[43m([49m[43mparents[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m     37[0m [38;5;28;01mexcept[39;00m [38;5;167;01mPermissionError[39;00m:

File [0;32m/usr/share/miniconda/envs/tutorial/lib/python3.8/pathlib.py:1288[0m, in [0;36mPath.mkdir[0;34m(self, mode, parents, exist_ok)[0m
[1;32m   1287[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1288[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_accessor[49m[38;5;241;43m.[39;49m[43mmkdir[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m   1289[0m [38;5;28;01mexcept[39;00m [38;5;167;01mFileNotFoundError[39;00m:

[0;31mPermissionError[0m: [Errno 13] Permission denied: '/ftproot'

During handling of the above exception, another exception occurred:

[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mhydrodataset[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcamels[39;00m [38;5;28;01mimport[39;00m Camels
[1;32m      3[0m camels_us_path [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin([38;5;124m"[39m[38;5;124mcamels[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mcamels_us[39m[38;5;124m"[39m)
[1;32m      4[0m us_region [38;5;241m=[39m [38;5;124m"[39m[38;5;124mUS[39m[38;5;124m"[39m

File [0;32m/usr/share/miniconda/envs/tutorial/lib/python3.8/site-packages/hydrodataset/__init__.py:39[0m
[1;32m     36[0m         hydrodataset_root_dir[38;5;241m.[39mmkdir(parents[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     37[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mPermissionError[39;00m:
[1;32m     38[0m         [38;5;28mprint[39m(
[0;32m---> 39[0m             [38;5;124;43m"[39;49m[38;5;124;43mYou cannot create this directory: [39;49m[38;5;124;43m"[39;49m
[1;32m     40[0m [43m            [49m[38;5;241;43m+[39;49m[43m [49m[43mhydrodataset_root_dir[49m
[1;32m     41[0m             [38;5;241m+[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m Please change the first line in [39m[38;5;124m"[39m
[1;32m     42[0m             [38;5;241m+[39m hydrodataset_setting_file
[1;32m     43[0m             [38;5;241m+[39m [38;5;124m"[39m[38;5;124m to a directory you have permission and run the code agian[39m[38;5;124m"[39m
[1;32m     44[0m         )
[1;32m     45[0m [38;5;66;03m# set some constants for hydrodataset[39;00m
[1;32m     46[0m ROOT_DIR [38;5;241m=[39m hydrodataset_root_dir

[0;31mTypeError[0m: can only concatenate str (not "PosixPath") to str
TypeError: can only concatenate str (not "PosixPath") to str

